image: maven:latest
definitions:
  step:
    - step: &build
        name: Build, test and keep the artifact
        caches:
          - maven
        script:
          - mvn -B verify
        artifacts:
          - target/registry.jar

    - step: &docker
        name: Push into docker
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
          - docker build -t lacribeiro11/registry:latest .
          - docker push lacribeiro11/registry:latest
        services:
          - docker

    - step: &deploy
        name: Deploy into unleash-it
        script:
          - pipe: atlassian/ssh-run:0.2.8
            variables:
              SSH_USER: $UNLEASHIT_USER
              SERVER: $UNLEASHIT_IP
              PORT: $UNLEASHIT_PORT
              # TODO it should be the name of the server instead of stackdemo
              COMMAND: ' docker service update stackdemo_registry'

pipelines:
  default:
    - step: *build
  branches:
    develop:
      - step: *build
      - step: *docker
      - step: *deploy
