# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:latest

pipelines:
  default:
    - step:
        name: build
        caches:
          - maven
        script:
          - mvn -B verify
          # TODO Docker should run only for develop and releases on February
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
          - docker build -t lacribeiro11/registry:latest .
          - docker push lacribeiro11/registry:latest
        services:
          - docker
