# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:latest

pipelines:
  default:
    - step:
        name: build
        caches:
          - maven
        script:
          - mvn clean install

  branches:
    # It will run only for developer
    ba2/microservices:
      - step:
          # It will compile the source and archive its content
          name: build
          caches:
            - maven
          script:
            - mvn clean install
            - mkdir files_to_deploy
            - cp target/casp*.jar files_to_deploy/
          artifacts:
            # when running the ng build the compiled content will be saved inside the dist/demo directory, now we archive it for the next step
            - files_to_deploy/*

      - step:
          # It will deploy the content in unleash-it server
          name: deploy
          script:
            # install ssh client, case it doesn't exist
            - chmod +x ./bitbucket_files/*
