spring:
  application:
    name: casp-registry-service

# default port for eureka server
server:
  port: ${EUREKA_PORT:19990}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:eureka1}
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
